name: nightly-macOS-x86_64

on: [workflow_dispatch]

jobs:
  nightly-macOS-x86_64:
    strategy:
      fail-fast: false

    runs-on: macos-latest

    env:
      OPENSSL_ROOT_DIR: /usr/local/opt/openssl/

    steps:
      - name: Install Dependencies
        run: |
          brew install boost@1.76 openssl@1.1 thrift grep
          echo "Test" | ggrep -P "."
          ARR=( $(printf "%s\n%s\n" "1" "ozan cansel 2") )

      - uses: actions/checkout@v2
