name: nightly-macOS-x86_64

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  nightly-macOS-x86_64:
    strategy:
      fail-fast: false
      matrix:
        build_type:
          - type: Debug
            warn_as_err: ON
          - type: Release
            warn_as_err: OFF

        shared_libs:
          - toggle: OFF
            name: Static
          - toggle: ON
            name: Shared

    runs-on: macos-latest

    env:
      OPENSSL_ROOT_DIR: /usr/local/opt/openssl/

    steps:
      - name: Install Dependencies
        run: |
          brew install boost@1.76 openssl@1.1 thrift

      - uses: actions/checkout@v2
