name: Test

on:
  pull_request_target:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  test:
    runs-on: macos-12
    strategy:
      fail-fast: false
      matrix:
        release:
          - version: 13.0

    name: FreeBSD
    steps:
    - uses: actions/checkout@v3
    - name: Build
      id: test
      uses: vmactions/freebsd-vm@v0
      with:
        usesh: true
        prepare: |
          pkg install -y curl \
                         gcc \
                         git \
                         gmake \
                         cmake \
                         autoconf \
                         automake \
                         libtool \
                         libiconv \
                         gettext \
                         openssl \
                         libmaxminddb \
                         tinycdb \
                         screen \
                         bash
          git clone https://git.FreeBSD.org/ports.git -b 2023Q1 /usr/ports

          cd /usr/ports/databases/sqlite3
          make BATCH=yes OPTIONS_SET=STATIC install clean

        run: |
          ls -lah
          ls -lh /usr/local/lib/libsqlite3*
