name: Test

on:
  pull_request_target:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  test:
    runs-on: macos-12
    strategy:
      fail-fast: false
      matrix:
        release:
          - version: 12.3
          - version: 13.0
          - version: 13.1

    name: FreeBSD
    steps:
    - uses: actions/checkout@v3
    - name: Build
      id: test
      uses: vmactions/freebsd-vm@v0
      with:
        usesh: true
        prepare: |
          pkg install -y curl gcc git

        run: |
          ls -lah
          git clone https://github.com/OzanCansel/apue-631.git
          cd apue-631/bbcp
          make
