name: Test

on:
  pull_request_target:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  test:
    runs-on: macos-12
    name: A job to run test in FreeBSD
    env:
      MYTOKEN : ${{ secrets.MYTOKEN }}
      MYTOKEN2: "value2"
    steps:
    - uses: actions/checkout@v3
    - name: Build FreeBSD
      id: test
      uses: vmactions/freebsd-vm@v0
      with:
        usesh: true
        prepare: |
          pkg install -y curl gcc git

        run: |
          ls -lah
          git clone https://github.com/OzanCansel/apue-631.git
          cd apue-631/bbcp
          make
