name: nightly-macOS-x86_64

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  macos-test:
    strategy:
      fail-fast: false

    runs-on: macos-latest

    env:
      OPENSSL_ROOT_DIR: /usr/local/opt/openssl/

    steps:
      - name: Install Dependencies
        run: |
          echo "Test"
          # which sort
          # which printf
          # version_greater_equal()
          # {
          #    printf '%s\n%s\n' "$2" "$1" | sort --check=quiet --version-sort
          # }
          #HZ_VERSION=4.1.3
          #version_greater_equal ${HZ_VERSION} 4.2.0          
          #echo $?
