name: nightly-macOS-x86_64

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  macos-test:
    strategy:
      fail-fast: false

    runs-on: macos-latest

    env:
      OPENSSL_ROOT_DIR: /usr/local/opt/openssl/

    steps:
      - name: Install Dependencies
        run: |
          ./mac.sh
